const express=require('express'),{v4:uuidv4}=require('uuid'),{getDb}=require('../database'),{authenticate,optionalAuth}=require('../middleware/auth'),{getSetting}=require('../settings');
const r=express.Router();
r.get('/',optionalAuth,(req,res)=>{try{const db=getDb(),page=parseInt(req.query.page)||1,limit=Math.min(parseInt(req.query.limit)||20,50),offset=(page-1)*limit,sort=req.query.sort||'latest',cat=req.query.category,search=req.query.search;
let w="WHERE p.status='published'",p=[];if(cat){w+=" AND p.category=?";p.push(cat);}if(search){w+=" AND (p.title LIKE ? OR p.content LIKE ?)";p.push(`%${search}%`,`%${search}%`);}
let o='ORDER BY p.created_at DESC';if(sort==='hot')o='ORDER BY p.likes DESC';if(sort==='comments')o='ORDER BY p.comments_count DESC';
const total=db.prepare(`SELECT COUNT(*) as c FROM posts p ${w}`).get(...p).c;
const posts=db.prepare(`SELECT p.*,u.nickname as author_name,u.avatar as author_avatar,u.id as author_id FROM posts p LEFT JOIN users u ON p.user_id=u.id ${w} ${o} LIMIT ? OFFSET ?`).all(...p,limit,offset);
res.json({posts:posts.map(x=>{let img=[],tag=[];try{img=JSON.parse(x.images);}catch(e){}try{tag=JSON.parse(x.tags);}catch(e){}const liked=req.user?!!db.prepare("SELECT id FROM likes WHERE user_id=? AND target_id=? AND target_type='post'").get(req.user.id,x.id):false;return{...x,images:img,tags:tag,isLiked:liked,author_name:x.is_anonymous?'匿名用户':x.author_name,author_avatar:x.is_anonymous?'/img/loge.png':x.author_avatar,author_id:x.is_anonymous?null:x.author_id};}),pagination:{page,limit,total,totalPages:Math.ceil(total/limit)}});}catch(e){console.error(e);res.status(500).json({error:'获取失败'});}});
r.get('/meta/tags',(req,res)=>{try{const db=getDb();const tc={};db.prepare("SELECT tags FROM posts WHERE status='published'").all().forEach(x=>{try{JSON.parse(x.tags).forEach(t=>{tc[t]=(tc[t]||0)+1;});}catch(e){}});res.json({tags:Object.entries(tc).sort((a,b)=>b[1]-a[1]).slice(0,20).map(([n,c])=>({name:n,count:c}))});}catch(e){res.json({tags:[]});}});
r.get('/:id',optionalAuth,(req,res)=>{try{const db=getDb();const p=db.prepare("SELECT p.*,u.nickname as author_name,u.avatar as author_avatar,u.id as author_id FROM posts p LEFT JOIN users u ON p.user_id=u.id WHERE p.id=? AND p.status!='deleted'").get(req.params.id);if(!p)return res.status(404).json({error:'帖子不存在'});let img=[],tag=[];try{img=JSON.parse(p.images);}catch(e){}try{tag=JSON.parse(p.tags);}catch(e){}const liked=req.user?!!db.prepare("SELECT id FROM likes WHERE user_id=? AND target_id=? AND target_type='post'").get(req.user.id,p.id):false;
const comments=db.prepare("SELECT c.*,u.nickname as author_name,u.avatar as author_avatar FROM comments c LEFT JOIN users u ON c.user_id=u.id WHERE c.post_id=? AND c.status='published' ORDER BY c.created_at ASC").all(req.params.id);
res.json({post:{...p,images:img,tags:tag,isLiked:liked,author_name:p.is_anonymous?'匿名用户':p.author_name,author_avatar:p.is_anonymous?'/img/loge.png':p.author_avatar,author_id:p.is_anonymous?null:p.author_id},comments:comments.map(c=>({...c,isLiked:req.user?!!db.prepare("SELECT id FROM likes WHERE user_id=? AND target_id=? AND target_type='comment'").get(req.user.id,c.id):false}))});}catch(e){res.status(500).json({error:'获取失败'});}});
r.post('/',authenticate,(req,res)=>{try{const db=getDb(),{title,content,images,isAnonymous,tags,category}=req.body;if(!title||!content)return res.status(400).json({error:'请输入标题和内容'});if(title.length>100)return res.status(400).json({error:'标题最长100字'});if(content.length>5000)return res.status(400).json({error:'内容最长5000字'});const mi=parseInt(getSetting('maxImagesPerPost'))||9,il=Array.isArray(images)?images.slice(0,mi):[],st=getSetting('postReview')==='true'?'pending':'published',id=uuidv4();db.prepare("INSERT INTO posts (id,user_id,title,content,images,is_anonymous,tags,category,status) VALUES (?,?,?,?,?,?,?,?,?)").run(id,req.user.id,title,content,JSON.stringify(il),isAnonymous?1:0,JSON.stringify(tags||[]),category||'confession',st);res.json({message:st==='pending'?'发布成功，等待审核':'发布成功',post:{id,title,status:st}});}catch(e){res.status(500).json({error:'发布失败'});}});
r.post('/:id/like',authenticate,(req,res)=>{try{const db=getDb(),p=db.prepare('SELECT id,likes FROM posts WHERE id=?').get(req.params.id);if(!p)return res.status(404).json({error:'帖子不存在'});const ex=db.prepare("SELECT id FROM likes WHERE user_id=? AND target_id=? AND target_type='post'").get(req.user.id,req.params.id);if(ex){db.prepare('DELETE FROM likes WHERE id=?').run(ex.id);db.prepare('UPDATE posts SET likes=MAX(0,likes-1) WHERE id=?').run(req.params.id);res.json({liked:false,likes:p.likes-1});}else{db.prepare("INSERT INTO likes (id,user_id,target_id,target_type) VALUES (?,?,?,'post')").run(uuidv4(),req.user.id,req.params.id);db.prepare('UPDATE posts SET likes=likes+1 WHERE id=?').run(req.params.id);res.json({liked:true,likes:p.likes+1});}}catch(e){res.status(500).json({error:'操作失败'});}});
r.post('/:id/comments',authenticate,(req,res)=>{try{const db=getDb(),{content}=req.body;if(!content?.trim())return res.status(400).json({error:'请输入评论'});if(content.length>1000)return res.status(400).json({error:'评论最长1000字'});const p=db.prepare("SELECT id FROM posts WHERE id=? AND status='published'").get(req.params.id);if(!p)return res.status(404).json({error:'帖子不存在'});const id=uuidv4();db.prepare('INSERT INTO comments (id,post_id,user_id,content) VALUES (?,?,?,?)').run(id,req.params.id,req.user.id,content.trim());db.prepare('UPDATE posts SET comments_count=comments_count+1 WHERE id=?').run(req.params.id);const c=db.prepare('SELECT c.*,u.nickname as author_name,u.avatar as author_avatar FROM comments c LEFT JOIN users u ON c.user_id=u.id WHERE c.id=?').get(id);res.json({message:'评论成功',comment:c});}catch(e){res.status(500).json({error:'评论失败'});}});
r.post('/comments/:id/like',authenticate,(req,res)=>{try{const db=getDb(),c=db.prepare('SELECT id,likes FROM comments WHERE id=?').get(req.params.id);if(!c)return res.status(404).json({error:'评论不存在'});const ex=db.prepare("SELECT id FROM likes WHERE user_id=? AND target_id=? AND target_type='comment'").get(req.user.id,req.params.id);if(ex){db.prepare('DELETE FROM likes WHERE id=?').run(ex.id);db.prepare('UPDATE comments SET likes=MAX(0,likes-1) WHERE id=?').run(req.params.id);res.json({liked:false,likes:c.likes-1});}else{db.prepare("INSERT INTO likes (id,user_id,target_id,target_type) VALUES (?,?,?,'comment')").run(uuidv4(),req.user.id,req.params.id);db.prepare('UPDATE comments SET likes=likes+1 WHERE id=?').run(req.params.id);res.json({liked:true,likes:c.likes+1});}}catch(e){res.status(500).json({error:'操作失败'});}});
r.delete('/:id',authenticate,(req,res)=>{try{const db=getDb(),p=db.prepare('SELECT user_id FROM posts WHERE id=?').get(req.params.id);if(!p)return res.status(404).json({error:'不存在'});if(p.user_id!==req.user.id&&!['admin','super_admin'].includes(req.user.role))return res.status(403).json({error:'无权删除'});db.prepare("UPDATE posts SET status='deleted' WHERE id=?").run(req.params.id);res.json({message:'已删除'});}catch(e){res.status(500).json({error:'删除失败'});}});
r.post('/:id/report',authenticate,(req,res)=>{try{const db=getDb(),{reason}=req.body;if(!reason)return res.status(400).json({error:'请填写原因'});if(db.prepare("SELECT id FROM reports WHERE reporter_id=? AND target_id=? AND status='pending'").get(req.user.id,req.params.id))return res.status(400).json({error:'已举报过'});db.prepare("INSERT INTO reports (id,reporter_id,target_id,target_type,reason) VALUES (?,?,?,'post',?)").run(uuidv4(),req.user.id,req.params.id,reason);res.json({message:'举报已提交'});}catch(e){res.status(500).json({error:'举报失败'});}});
module.exports=r;
